name: cuttinglist
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+3

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  csv: ^5.0.0
  intl: 0.20.2
  path: ^1.7.0
  flutter_colorpicker: ^1.1.0
  flutter_drawing_board: ^0.9.5
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  flutter_data_table: ^2.0.0
  pdf: ^3.11.3
  printing: ^5.11.0
  open_file: ^3.5.10
  share_plus: ^10.1.4
  permission_handler: ^12.0.0+1
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.0.0+1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/logo.png"
