platform :ios, '12.0'
workspace 'Runner.xcworkspace'

ENV['FLUTTER_ROOT'] ||= File.expand_path('../../flutter')
load File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  install_all_flutter_pods(File.dirname(File.realpath(__FILE__)))
end
